CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    cash_balance NUMERIC(19, 4) NOT NULL DEFAULT 100000.0000,
    CONSTRAINT ck_app_user_cash_nonnegative CHECK (cash_balance >= 0)
);

CREATE TABLE portfolio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_portfolio_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE TABLE stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL UNIQUE,
    company_name VARCHAR(255) NOT NULL,
    current_price NUMERIC(19, 4) NOT NULL DEFAULT 0,
    sector VARCHAR(255),
    demo_earnings_per_share NUMERIC(19, 4),
    demo_market_capitalization NUMERIC(24, 2),
    demo_dividend_yield NUMERIC(10, 6),
    price_updated_at TIMESTAMP WITH TIME ZONE,
    price_source VARCHAR(30)
);

CREATE TABLE holding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    average_cost_basis NUMERIC(19, 4) NOT NULL,
    CONSTRAINT uk_holding_portfolio_stock UNIQUE (portfolio_id, stock_id),
    CONSTRAINT ck_holding_quantity_positive CHECK (quantity > 0),
    CONSTRAINT fk_holding_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolio(id),
    CONSTRAINT fk_holding_stock FOREIGN KEY (stock_id) REFERENCES stock(id)
);

CREATE TABLE trade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    type VARCHAR(10) NOT NULL,
    quantity INTEGER NOT NULL,
    price_at_execution NUMERIC(19, 4) NOT NULL,
    realized_gain_loss NUMERIC(19, 4) NOT NULL DEFAULT 0,
    executed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    idempotency_key VARCHAR(36),
    CONSTRAINT ck_trade_type CHECK (type IN ('BUY', 'SELL')),
    CONSTRAINT ck_trade_quantity_positive CHECK (quantity > 0),
    CONSTRAINT uk_trade_user_idempotency UNIQUE (user_id, idempotency_key),
    CONSTRAINT fk_trade_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_trade_stock FOREIGN KEY (stock_id) REFERENCES stock(id)
);
CREATE INDEX ix_trade_user_executed ON trade(user_id, executed_at DESC);

CREATE TABLE watchlist_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    added_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_watchlist_user_stock UNIQUE (user_id, stock_id),
    CONSTRAINT fk_watchlist_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_watchlist_stock FOREIGN KEY (stock_id) REFERENCES stock(id)
);

CREATE TABLE stock_daily_price (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT NOT NULL,
    trading_date DATE NOT NULL,
    close_price NUMERIC(19, 4) NOT NULL,
    data_source VARCHAR(30),
    CONSTRAINT uk_stock_price_date UNIQUE (stock_id, trading_date),
    CONSTRAINT fk_stock_daily_price_stock FOREIGN KEY (stock_id) REFERENCES stock(id)
);

CREATE TABLE portfolio_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    valuation_date DATE NOT NULL,
    cash_balance NUMERIC(19, 4) NOT NULL,
    invested_value NUMERIC(19, 4) NOT NULL,
    total_value NUMERIC(19, 4) NOT NULL,
    CONSTRAINT uk_snapshot_user_date UNIQUE (user_id, valuation_date),
    CONSTRAINT fk_snapshot_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);
